<a href="https://colab.research.google.com/github/kuroko941/ml-learning-journey/blob/main/Scikit-Learn/AmnesHousing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!kaggle datasets download -d shashanknecrothapa/ames-housing-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/shashanknecrothapa/ames-housing-dataset
License(s): unknown
ames-housing-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [44]:
import zipfile
zip_ref=zipfile.ZipFile('/content/ames-housing-dataset.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df=pd.read_csv('AmesHousing.csv')
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

EDA

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [48]:
print('-'*40)
print(df.isnull().sum())
print('-'*40)
print('percenrage of missing values:\n',df.isnull().sum()*100/len(df))
print('-'*40)
missing = df.isnull().sum()
missing[missing > 0]

----------------------------------------
Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64
----------------------------------------
percenrage of missing values:
 Order              0.000000
PID                0.000000
MS SubClass        0.000000
MS Zoning          0.000000
Lot Frontage      16.723549
                    ...
Mo Sold            0.000000
Yr Sold            0.000000
Sale Type          0.000000
Sale Condition     0.000000
SalePrice          0.000000
Length: 82, dtype: float64
----------------------------------------

Lot Frontage       490
Alley             2732
Mas Vnr Type      1775
Mas Vnr Area        23
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin SF 1         1
BsmtFin Type 2      81
BsmtFin SF 2         1
Bsmt Unf SF          1
Total Bsmt SF        1
Electrical           1
Bsmt Full Bath       2
Bsmt Half Bath       2
Fireplace Qu      1422
Garage Type        157
Garage Yr Blt      159
Garage Finish      159
Garage Cars          1
Garage Area          1
Garage Qual        159
Garage Cond        159
Pool QC           2917
Fence             2358
Misc Feature      2824
dtype: int64

In [49]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [50]:
df.nunique()

Order             2930
PID               2930
MS SubClass         16
MS Zoning            7
Lot Frontage       128
                  ...
Mo Sold             12
Yr Sold              5
Sale Type           10
Sale Condition       6
SalePrice         1032
Length: 82, dtype: int64

In [51]:
df=df.drop(columns=['Pool QC','Misc Feature','Alley','Fence'])
#df_new.columns

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 78 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Lot Shape        2930 non-null   object
 8   Land Contour     2930 non-null   object
 9   Utilities        2930 non-null   object
 10  Lot Config       2930 non-null   object
 11  Land Slope       2930 non-null   object
 12  Neighborhood     2930 non-null   object
 13  Condition 1      2930 non-null   object
 14  Condition 2      2930 non-null   object
 15  Bldg Type        2930 non-null   object
 16  House Style      2930 non-null   object
 17  Overall Qual     2930 non-null   int64
 18  Overall Cond     2930 non-null   int64
 19  Year Built       2930 non-null   int64
 20  Year Remod/Add   2930 non-null   int64
 21  Roof Style       2930 non-null   object
 22  Roof Matl        2930 non-null   object
 23  Exterior 1st     2930 non-null   object
 24  Exterior 2nd     2930 non-null   object
 25  Mas Vnr Type     1155 non-null   object
 26  Mas Vnr Area     2907 non-null   float64
 27  Exter Qual       2930 non-null   object
 28  Exter Cond       2930 non-null   object
 29  Foundation       2930 non-null   object
 30  Bsmt Qual        2850 non-null   object
 31  Bsmt Cond        2850 non-null   object
 32  Bsmt Exposure    2847 non-null   object
 33  BsmtFin Type 1   2850 non-null   object
 34  BsmtFin SF 1     2929 non-null   float64
 35  BsmtFin Type 2   2849 non-null   object
 36  BsmtFin SF 2     2929 non-null   float64
 37  Bsmt Unf SF      2929 non-null   float64
 38  Total Bsmt SF    2929 non-null   float64
 39  Heating          2930 non-null   object
 40  Heating QC       2930 non-null   object
 41  Central Air      2930 non-null   object
 42  Electrical       2929 non-null   object
 43  1st Flr SF       2930 non-null   int64
 44  2nd Flr SF       2930 non-null   int64
 45  Low Qual Fin SF  2930 non-null   int64
 46  Gr Liv Area      2930 non-null   int64
 47  Bsmt Full Bath   2928 non-null   float64
 48  Bsmt Half Bath   2928 non-null   float64
 49  Full Bath        2930 non-null   int64
 50  Half Bath        2930 non-null   int64
 51  Bedroom AbvGr    2930 non-null   int64
 52  Kitchen AbvGr    2930 non-null   int64
 53  Kitchen Qual     2930 non-null   object
 54  TotRms AbvGrd    2930 non-null   int64
 55  Functional       2930 non-null   object
 56  Fireplaces       2930 non-null   int64
 57  Fireplace Qu     1508 non-null   object
 58  Garage Type      2773 non-null   object
 59  Garage Yr Blt    2771 non-null   float64
 60  Garage Finish    2771 non-null   object
 61  Garage Cars      2929 non-null   float64
 62  Garage Area      2929 non-null   float64
 63  Garage Qual      2771 non-null   object
 64  Garage Cond      2771 non-null   object
 65  Paved Drive      2930 non-null   object
 66  Wood Deck SF     2930 non-null   int64
 67  Open Porch SF    2930 non-null   int64
 68  Enclosed Porch   2930 non-null   int64
 69  3Ssn Porch       2930 non-null   int64
 70  Screen Porch     2930 non-null   int64
 71  Pool Area        2930 non-null   int64
 72  Misc Val         2930 non-null   int64
 73  Mo Sold          2930 non-null   int64
 74  Yr Sold          2930 non-null   int64
 75  Sale Type        2930 non-null   object
 76  Sale Condition   2930 non-null   object
 77  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(39)
memory usage: 1.7+ MB

In [53]:
df['Mas Vnr Type']=df['Mas Vnr Type'].fillna(df['Mas Vnr Type'].mode()[0])
df['Lot Frontage']=df['Lot Frontage'].fillna(df['Lot Frontage'].median())
df['Bsmt Qual']=df['Bsmt Qual'].fillna(df['Bsmt Qual'].mode()[0])
df['Bsmt Cond']=df['Bsmt Cond'].fillna(df['Bsmt Cond'].mode()[0])
df['Bsmt Exposure']=df['Bsmt Exposure'].fillna(df['Bsmt Exposure'].mode()[0])
df['Garage Qual']=df['Garage Qual'].fillna(df['Garage Qual'].mode()[0])
df['Garage Cond']=df['Garage Cond'].fillna(df['Garage Cond'].mode()[0])
df['Garage Yr Blt']=df['Garage Yr Blt'].fillna(df['Garage Yr Blt'].median())
df['Garage Type']=df['Garage Type'].fillna(df['Garage Type'].mode()[0])
df['Garage Finish']=df['Garage Finish'].fillna(df['Garage Finish'].mode()[0])
df['Mas Vnr Area']=df['Mas Vnr Area'].fillna(df['Mas Vnr Area'].mode()[0])
df['Fireplace Qu'] = df['Fireplace Qu'].fillna('None')
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])
df['Garage Yr Blt'] = df['Garage Yr Blt'].fillna(df['Garage Yr Blt'].median())
df['BsmtFin Type 1'] = df['BsmtFin Type 1'].fillna('None')
df['BsmtFin Type 2'] = df['BsmtFin Type 2'].fillna('None')

In [54]:
num_cols = [
    'BsmtFin SF 1',
    'BsmtFin SF 2',
    'Bsmt Unf SF',
    'Total Bsmt SF',
    'Bsmt Full Bath',
    'Bsmt Half Bath',
    'Garage Cars',
    'Garage Area'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 78 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2930 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Lot Shape        2930 non-null   object
 8   Land Contour     2930 non-null   object
 9   Utilities        2930 non-null   object
 10  Lot Config       2930 non-null   object
 11  Land Slope       2930 non-null   object
 12  Neighborhood     2930 non-null   object
 13  Condition 1      2930 non-null   object
 14  Condition 2      2930 non-null   object
 15  Bldg Type        2930 non-null   object
 16  House Style      2930 non-null   object
 17  Overall Qual     2930 non-null   int64
 18  Overall Cond     2930 non-null   int64
 19  Year Built       2930 non-null   int64
 20  Year Remod/Add   2930 non-null   int64
 21  Roof Style       2930 non-null   object
 22  Roof Matl        2930 non-null   object
 23  Exterior 1st     2930 non-null   object
 24  Exterior 2nd     2930 non-null   object
 25  Mas Vnr Type     2930 non-null   object
 26  Mas Vnr Area     2930 non-null   float64
 27  Exter Qual       2930 non-null   object
 28  Exter Cond       2930 non-null   object
 29  Foundation       2930 non-null   object
 30  Bsmt Qual        2930 non-null   object
 31  Bsmt Cond        2930 non-null   object
 32  Bsmt Exposure    2930 non-null   object
 33  BsmtFin Type 1   2930 non-null   object
 34  BsmtFin SF 1     2930 non-null   float64
 35  BsmtFin Type 2   2930 non-null   object
 36  BsmtFin SF 2     2930 non-null   float64
 37  Bsmt Unf SF      2930 non-null   float64
 38  Total Bsmt SF    2930 non-null   float64
 39  Heating          2930 non-null   object
 40  Heating QC       2930 non-null   object
 41  Central Air      2930 non-null   object
 42  Electrical       2930 non-null   object
 43  1st Flr SF       2930 non-null   int64
 44  2nd Flr SF       2930 non-null   int64
 45  Low Qual Fin SF  2930 non-null   int64
 46  Gr Liv Area      2930 non-null   int64
 47  Bsmt Full Bath   2930 non-null   float64
 48  Bsmt Half Bath   2930 non-null   float64
 49  Full Bath        2930 non-null   int64
 50  Half Bath        2930 non-null   int64
 51  Bedroom AbvGr    2930 non-null   int64
 52  Kitchen AbvGr    2930 non-null   int64
 53  Kitchen Qual     2930 non-null   object
 54  TotRms AbvGrd    2930 non-null   int64
 55  Functional       2930 non-null   object
 56  Fireplaces       2930 non-null   int64
 57  Fireplace Qu     2930 non-null   object
 58  Garage Type      2930 non-null   object
 59  Garage Yr Blt    2930 non-null   float64
 60  Garage Finish    2930 non-null   object
 61  Garage Cars      2930 non-null   float64
 62  Garage Area      2930 non-null   float64
 63  Garage Qual      2930 non-null   object
 64  Garage Cond      2930 non-null   object
 65  Paved Drive      2930 non-null   object
 66  Wood Deck SF     2930 non-null   int64
 67  Open Porch SF    2930 non-null   int64
 68  Enclosed Porch   2930 non-null   int64
 69  3Ssn Porch       2930 non-null   int64
 70  Screen Porch     2930 non-null   int64
 71  Pool Area        2930 non-null   int64
 72  Misc Val         2930 non-null   int64
 73  Mo Sold          2930 non-null   int64
 74  Yr Sold          2930 non-null   int64
 75  Sale Type        2930 non-null   object
 76  Sale Condition   2930 non-null   object
 77  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(39)
memory usage: 1.7+ MB

In [56]:
df.isnull().sum().sum()

np.int64(0)

In [57]:
df=df.drop(['Order', 'PID'], axis=1)

In [42]:
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

# Feature encoding

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
X_train.dtypes

MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
Street             object
                   ...
Misc Val            int64
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
Length: 75, dtype: object

In [24]:
X_train=pd.get_dummies(X_train,dtype=int,drop_first=True)
X_test=pd.get_dummies(X_test,dtype=int,drop_first=True)

#                     AND
#from sklearn.preprocessing import OneHotEncoder
#enc=OneHotEncoder()
#enc.fit(X_train,X_test)

In [25]:
X_train,X_test=X_train.align(X_test,join='left',axis=1,fill_value=0)
print(X_train.shape)
print(X_test.shape)

(2344, 250)
(586, 250)

# model

Random forest

In [26]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [27]:
#prediction
pred=model.predict(X_test)

#evaluation
from sklearn.metrics import r2_score,mean_squared_error
print('r2 score:',r2_score(y_test,pred))
print('RMSE score:',np.sqrt(mean_squared_error(y_test,pred)))

r2 score: 0.9123588334848465
RMSE score: 26507.871533865407

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
pipe=Pipeline([('scaler',StandardScaler()),('rfr',RandomForestRegressor())])

pipe.fit(X_train,y_train).score(X_test,y_test)

In [37]:
# hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV
param_grid = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

clf = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_grid,
    n_iter=10,
    cv=5,
    scoring='r2',
    random_state=42,
    n_jobs=-1
)

clf.fit(X_train, y_train)

print(clf.best_params_)
print(clf.best_score_)
best_model = clf.best_estimator_

pred = best_model.predict(X_test)

print("R2:", r2_score(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

{'n_estimators': 300, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_depth': 30}
0.8814590114844687
R2: 0.9093215497817649
RMSE: 26963.28653790433

# Feature importance